# add a default for unmatched language strings
REPLACE INTO language (iso_code,language) VALUES ('other','');
# the rest is extracted from mediawiki includes/languages/data/Names.php
REPLACE INTO language (iso_code,language) VALUES ('aa','Qafár af');
REPLACE INTO language (iso_code,language) VALUES ('ab','аԥсшәа');
REPLACE INTO language (iso_code,language) VALUES ('abs','bahasa ambon');
REPLACE INTO language (iso_code,language) VALUES ('ace','Acèh');
REPLACE INTO language (iso_code,language) VALUES ('ady','адыгабзэ');
REPLACE INTO language (iso_code,language) VALUES ('ady-cyrl','адыгабзэ');
REPLACE INTO language (iso_code,language) VALUES ('aeb','تونسي/Tûnsî');
REPLACE INTO language (iso_code,language) VALUES ('aeb-arab','تونسي');
REPLACE INTO language (iso_code,language) VALUES ('aeb-latn','Tûnsî');
REPLACE INTO language (iso_code,language) VALUES ('af','Afrikaans');
REPLACE INTO language (iso_code,language) VALUES ('ak','Akan');
REPLACE INTO language (iso_code,language) VALUES ('aln','Gegë');
REPLACE INTO language (iso_code,language) VALUES ('als','Alemannisch');
REPLACE INTO language (iso_code,language) VALUES ('alt','алтай тил');
REPLACE INTO language (iso_code,language) VALUES ('am','አማርኛ');
REPLACE INTO language (iso_code,language) VALUES ('ami','Pangcah');
REPLACE INTO language (iso_code,language) VALUES ('an','aragonés');
REPLACE INTO language (iso_code,language) VALUES ('ang','Ænglisc');
REPLACE INTO language (iso_code,language) VALUES ('anp','अंगिका');
REPLACE INTO language (iso_code,language) VALUES ('ar','العربية');
REPLACE INTO language (iso_code,language) VALUES ('arc','ܐܪܡܝܐ');
REPLACE INTO language (iso_code,language) VALUES ('arn','mapudungun');
REPLACE INTO language (iso_code,language) VALUES ('arq','جازايرية');
REPLACE INTO language (iso_code,language) VALUES ('ary','الدارجة');
REPLACE INTO language (iso_code,language) VALUES ('arz','مصرى');
REPLACE INTO language (iso_code,language) VALUES ('as','অসমীয়া');
REPLACE INTO language (iso_code,language) VALUES ('ase','American sign language');
REPLACE INTO language (iso_code,language) VALUES ('ast','asturianu');
REPLACE INTO language (iso_code,language) VALUES ('atj','Atikamekw');
REPLACE INTO language (iso_code,language) VALUES ('av','авар');
REPLACE INTO language (iso_code,language) VALUES ('avk','Kotava');
REPLACE INTO language (iso_code,language) VALUES ('awa','अवधी');
REPLACE INTO language (iso_code,language) VALUES ('ay','Aymar aru');
REPLACE INTO language (iso_code,language) VALUES ('az','azərbaycanca');
REPLACE INTO language (iso_code,language) VALUES ('azb','تۆرکجه');
REPLACE INTO language (iso_code,language) VALUES ('ba','башҡортса');
REPLACE INTO language (iso_code,language) VALUES ('ban','Basa Bali');
REPLACE INTO language (iso_code,language) VALUES ('ban-bali','ᬩᬲᬩᬮᬶ');
REPLACE INTO language (iso_code,language) VALUES ('bar','Boarisch');
REPLACE INTO language (iso_code,language) VALUES ('bat-smg','žemaitėška');
REPLACE INTO language (iso_code,language) VALUES ('bbc','Batak Toba');
REPLACE INTO language (iso_code,language) VALUES ('bbc-latn','Batak Toba');
REPLACE INTO language (iso_code,language) VALUES ('bcc','جهلسری بلوچی');
REPLACE INTO language (iso_code,language) VALUES ('bci','wawle');
REPLACE INTO language (iso_code,language) VALUES ('bcl','Bikol Central');
REPLACE INTO language (iso_code,language) VALUES ('be','беларуская');
REPLACE INTO language (iso_code,language) VALUES ('be-tarask','беларуская (тарашкевіца)');
REPLACE INTO language (iso_code,language) VALUES ('be-x-old','беларуская (тарашкевіца)');
REPLACE INTO language (iso_code,language) VALUES ('bg','български');
REPLACE INTO language (iso_code,language) VALUES ('bgn','روچ کپتین بلوچی');
REPLACE INTO language (iso_code,language) VALUES ('bh','भोजपुरी');
REPLACE INTO language (iso_code,language) VALUES ('bho','भोजपुरी');
REPLACE INTO language (iso_code,language) VALUES ('bi','Bislama');
REPLACE INTO language (iso_code,language) VALUES ('bjn','Banjar');
REPLACE INTO language (iso_code,language) VALUES ('blk','ပအိုဝ်ႏဘာႏသာႏ');
REPLACE INTO language (iso_code,language) VALUES ('bm','bamanankan');
REPLACE INTO language (iso_code,language) VALUES ('bn','বাংলা');
REPLACE INTO language (iso_code,language) VALUES ('bo','བོད་ཡིག');
REPLACE INTO language (iso_code,language) VALUES ('bpy','বিষ্ণুপ্রিয়া মণিপুরী');
REPLACE INTO language (iso_code,language) VALUES ('bqi','بختیاری');
REPLACE INTO language (iso_code,language) VALUES ('br','brezhoneg');
REPLACE INTO language (iso_code,language) VALUES ('brh','Bráhuí');
REPLACE INTO language (iso_code,language) VALUES ('bs','bosanski');
REPLACE INTO language (iso_code,language) VALUES ('btm','Batak Mandailing');
REPLACE INTO language (iso_code,language) VALUES ('bto','Iriga Bicolano');
REPLACE INTO language (iso_code,language) VALUES ('bug','ᨅᨔ ᨕᨘᨁᨗ');
REPLACE INTO language (iso_code,language) VALUES ('bxr','буряад');
REPLACE INTO language (iso_code,language) VALUES ('ca','català');
REPLACE INTO language (iso_code,language) VALUES ('cbk-zam','Chavacano de Zamboanga');
REPLACE INTO language (iso_code,language) VALUES ('cdo','閩東語 / Mìng-dĕ̤ng-ngṳ̄');
REPLACE INTO language (iso_code,language) VALUES ('ce','нохчийн');
REPLACE INTO language (iso_code,language) VALUES ('ceb','Cebuano');
REPLACE INTO language (iso_code,language) VALUES ('ch','Chamoru');
REPLACE INTO language (iso_code,language) VALUES ('cho','Chahta Anumpa');
REPLACE INTO language (iso_code,language) VALUES ('chr','ᏣᎳᎩ');
REPLACE INTO language (iso_code,language) VALUES ('chy','Tsetsêhestâhese');
REPLACE INTO language (iso_code,language) VALUES ('ckb','کوردی');
REPLACE INTO language (iso_code,language) VALUES ('co','corsu');
REPLACE INTO language (iso_code,language) VALUES ('cps','Capiceño');
REPLACE INTO language (iso_code,language) VALUES ('cr','Nēhiyawēwin / ᓀᐦᐃᔭᐍᐏᐣ');
REPLACE INTO language (iso_code,language) VALUES ('crh','qırımtatarca');
REPLACE INTO language (iso_code,language) VALUES ('crh-cyrl','къырымтатарджа (Кирилл)');
REPLACE INTO language (iso_code,language) VALUES ('crh-latn','qırımtatarca (Latin)');
REPLACE INTO language (iso_code,language) VALUES ('cs','čeština');
REPLACE INTO language (iso_code,language) VALUES ('csb','kaszëbsczi');
REPLACE INTO language (iso_code,language) VALUES ('cu','словѣньскъ / ⰔⰎⰑⰂⰡⰐⰠⰔⰍⰟ');
REPLACE INTO language (iso_code,language) VALUES ('cv','чӑвашла');
REPLACE INTO language (iso_code,language) VALUES ('cy','Cymraeg');
REPLACE INTO language (iso_code,language) VALUES ('da','dansk');
REPLACE INTO language (iso_code,language) VALUES ('dag','dagbanli');
REPLACE INTO language (iso_code,language) VALUES ('de','Deutsch');
REPLACE INTO language (iso_code,language) VALUES ('de-at','Österreichisches Deutsch');
REPLACE INTO language (iso_code,language) VALUES ('de-ch','Schweizer Hochdeutsch');
REPLACE INTO language (iso_code,language) VALUES ('de-formal','Deutsch (Sie-Form)');
REPLACE INTO language (iso_code,language) VALUES ('din','Thuɔŋjäŋ');
REPLACE INTO language (iso_code,language) VALUES ('diq','Zazaki');
REPLACE INTO language (iso_code,language) VALUES ('dsb','dolnoserbski');
REPLACE INTO language (iso_code,language) VALUES ('dtp','Dusun Bundu-liwan');
REPLACE INTO language (iso_code,language) VALUES ('dty','डोटेली');
REPLACE INTO language (iso_code,language) VALUES ('dv','ދިވެހިބަސް');
REPLACE INTO language (iso_code,language) VALUES ('dz','ཇོང་ཁ');
REPLACE INTO language (iso_code,language) VALUES ('ee','eʋegbe');
REPLACE INTO language (iso_code,language) VALUES ('egl','Emiliàn');
REPLACE INTO language (iso_code,language) VALUES ('el','Ελληνικά');
REPLACE INTO language (iso_code,language) VALUES ('eml','emiliàn e rumagnòl');
REPLACE INTO language (iso_code,language) VALUES ('en','English');
REPLACE INTO language (iso_code,language) VALUES ('en-ca','Canadian English');
REPLACE INTO language (iso_code,language) VALUES ('en-gb','British English');
REPLACE INTO language (iso_code,language) VALUES ('eo','Esperanto');
REPLACE INTO language (iso_code,language) VALUES ('es','español');
REPLACE INTO language (iso_code,language) VALUES ('es-419','español de América Latina');
REPLACE INTO language (iso_code,language) VALUES ('es-formal','español (formal)');
REPLACE INTO language (iso_code,language) VALUES ('et','eesti');
REPLACE INTO language (iso_code,language) VALUES ('eu','euskara');
REPLACE INTO language (iso_code,language) VALUES ('ext','estremeñu');
REPLACE INTO language (iso_code,language) VALUES ('fa','فارسی');
REPLACE INTO language (iso_code,language) VALUES ('fat','mfantse');
REPLACE INTO language (iso_code,language) VALUES ('ff','Fulfulde');
REPLACE INTO language (iso_code,language) VALUES ('fi','suomi');
REPLACE INTO language (iso_code,language) VALUES ('fit','meänkieli');
REPLACE INTO language (iso_code,language) VALUES ('fiu-vro','võro');
REPLACE INTO language (iso_code,language) VALUES ('fj','Na Vosa Vakaviti');
REPLACE INTO language (iso_code,language) VALUES ('fo','føroyskt');
REPLACE INTO language (iso_code,language) VALUES ('fon','fɔ̀ngbè');
REPLACE INTO language (iso_code,language) VALUES ('fr','français');
REPLACE INTO language (iso_code,language) VALUES ('frc','français cadien');
REPLACE INTO language (iso_code,language) VALUES ('frp','arpetan');
REPLACE INTO language (iso_code,language) VALUES ('frr','Nordfriisk');
REPLACE INTO language (iso_code,language) VALUES ('fur','furlan');
REPLACE INTO language (iso_code,language) VALUES ('fy','Frysk');
REPLACE INTO language (iso_code,language) VALUES ('ga','Gaeilge');
REPLACE INTO language (iso_code,language) VALUES ('gaa','Ga');
REPLACE INTO language (iso_code,language) VALUES ('gag','Gagauz');
REPLACE INTO language (iso_code,language) VALUES ('gan','贛語');
REPLACE INTO language (iso_code,language) VALUES ('gan-hans','赣语（简体）');
REPLACE INTO language (iso_code,language) VALUES ('gan-hant','贛語（繁體）');
REPLACE INTO language (iso_code,language) VALUES ('gcr','kriyòl gwiyannen');
REPLACE INTO language (iso_code,language) VALUES ('gd','Gàidhlig');
REPLACE INTO language (iso_code,language) VALUES ('gl','galego');
REPLACE INTO language (iso_code,language) VALUES ('gld','на̄ни');
REPLACE INTO language (iso_code,language) VALUES ('glk','گیلکی');
REPLACE INTO language (iso_code,language) VALUES ('gn','Avañe\'ẽ');
REPLACE INTO language (iso_code,language) VALUES ('gom','गोंयची कोंकणी / Gõychi Konknni');
REPLACE INTO language (iso_code,language) VALUES ('gom-deva','गोंयची कोंकणी');
REPLACE INTO language (iso_code,language) VALUES ('gom-latn','Gõychi Konknni');
REPLACE INTO language (iso_code,language) VALUES ('gor','Bahasa Hulontalo');
#REPLACE INTO language (iso_code,language) VALUES ('got','𐌲𐌿𐍄𐌹𐍃𐌺');
REPLACE INTO language (iso_code) VALUES ('got');
REPLACE INTO language (iso_code,language) VALUES ('gpe','Ghanaian Pidgin');
REPLACE INTO language (iso_code,language) VALUES ('grc','Ἀρχαία ἑλληνικὴ');
REPLACE INTO language (iso_code,language) VALUES ('gsw','Alemannisch');
REPLACE INTO language (iso_code,language) VALUES ('gu','ગુજરાતી');
REPLACE INTO language (iso_code,language) VALUES ('guc','wayuunaiki');
REPLACE INTO language (iso_code,language) VALUES ('gur','farefare');
REPLACE INTO language (iso_code,language) VALUES ('guw','gungbe');
REPLACE INTO language (iso_code,language) VALUES ('gv','Gaelg');
REPLACE INTO language (iso_code,language) VALUES ('ha','Hausa');
REPLACE INTO language (iso_code,language) VALUES ('hak','客家語/Hak-kâ-ngî');
REPLACE INTO language (iso_code,language) VALUES ('haw','Hawaiʻi');
REPLACE INTO language (iso_code,language) VALUES ('he','עברית');
REPLACE INTO language (iso_code,language) VALUES ('hi','हिन्दी');
REPLACE INTO language (iso_code,language) VALUES ('hif','Fiji Hindi');
REPLACE INTO language (iso_code,language) VALUES ('hif-latn','Fiji Hindi');
REPLACE INTO language (iso_code,language) VALUES ('hil','Ilonggo');
REPLACE INTO language (iso_code,language) VALUES ('ho','Hiri Motu');
REPLACE INTO language (iso_code,language) VALUES ('hr','hrvatski');
REPLACE INTO language (iso_code,language) VALUES ('hrx','Hunsrik');
REPLACE INTO language (iso_code,language) VALUES ('hsb','hornjoserbsce');
REPLACE INTO language (iso_code,language) VALUES ('hsn','湘语');
REPLACE INTO language (iso_code,language) VALUES ('ht','Kreyòl ayisyen');
REPLACE INTO language (iso_code,language) VALUES ('hu','magyar');
REPLACE INTO language (iso_code,language) VALUES ('hu-formal','magyar (formal)');
REPLACE INTO language (iso_code,language) VALUES ('hy','հայերեն');
REPLACE INTO language (iso_code,language) VALUES ('hyw','Արեւմտահայերէն');
REPLACE INTO language (iso_code,language) VALUES ('hz','Otsiherero');
REPLACE INTO language (iso_code,language) VALUES ('ia','interlingua');
REPLACE INTO language (iso_code,language) VALUES ('id','Bahasa Indonesia');
REPLACE INTO language (iso_code,language) VALUES ('ie','Interlingue');
REPLACE INTO language (iso_code,language) VALUES ('ig','Igbo');
REPLACE INTO language (iso_code,language) VALUES ('igl','Igala');
REPLACE INTO language (iso_code,language) VALUES ('ii','ꆇꉙ');
REPLACE INTO language (iso_code,language) VALUES ('ik','Iñupiatun');
REPLACE INTO language (iso_code,language) VALUES ('ike-cans','ᐃᓄᒃᑎᑐᑦ');
REPLACE INTO language (iso_code,language) VALUES ('ike-latn','inuktitut');
REPLACE INTO language (iso_code,language) VALUES ('ilo','Ilokano');
REPLACE INTO language (iso_code,language) VALUES ('inh','гӀалгӀай');
REPLACE INTO language (iso_code,language) VALUES ('io','Ido');
REPLACE INTO language (iso_code,language) VALUES ('is','íslenska');
REPLACE INTO language (iso_code,language) VALUES ('it','italiano');
REPLACE INTO language (iso_code,language) VALUES ('iu','ᐃᓄᒃᑎᑐᑦ/inuktitut');
REPLACE INTO language (iso_code,language) VALUES ('ja','日本語');
REPLACE INTO language (iso_code,language) VALUES ('jam','Patois');
REPLACE INTO language (iso_code,language) VALUES ('jbo','la .lojban.');
REPLACE INTO language (iso_code,language) VALUES ('jut','jysk');
REPLACE INTO language (iso_code,language) VALUES ('jv','Jawa');
REPLACE INTO language (iso_code,language) VALUES ('ka','ქართული');
REPLACE INTO language (iso_code,language) VALUES ('kaa','Qaraqalpaqsha');
REPLACE INTO language (iso_code,language) VALUES ('kab','Taqbaylit');
REPLACE INTO language (iso_code,language) VALUES ('kbd','адыгэбзэ');
REPLACE INTO language (iso_code,language) VALUES ('kbd-cyrl','адыгэбзэ');
REPLACE INTO language (iso_code,language) VALUES ('kbp','Kabɩyɛ');
REPLACE INTO language (iso_code,language) VALUES ('kcg','Tyap');
REPLACE INTO language (iso_code,language) VALUES ('kea','kabuverdianu');
REPLACE INTO language (iso_code,language) VALUES ('kg','Kongo');
REPLACE INTO language (iso_code,language) VALUES ('khw','کھوار');
REPLACE INTO language (iso_code,language) VALUES ('ki','Gĩkũyũ');
REPLACE INTO language (iso_code,language) VALUES ('kiu','Kırmancki');
REPLACE INTO language (iso_code,language) VALUES ('kj','Kwanyama');
REPLACE INTO language (iso_code,language) VALUES ('kjh','хакас');
REPLACE INTO language (iso_code,language) VALUES ('kjp','ဖၠုံလိက်');
REPLACE INTO language (iso_code,language) VALUES ('kk','қазақша');
REPLACE INTO language (iso_code,language) VALUES ('kk-arab','قازاقشا (تٴوتە)');
REPLACE INTO language (iso_code,language) VALUES ('kk-cn','قازاقشا (جۇنگو)');
REPLACE INTO language (iso_code,language) VALUES ('kk-cyrl','қазақша (кирил)');
REPLACE INTO language (iso_code,language) VALUES ('kk-kz','қазақша (Қазақстан)');
REPLACE INTO language (iso_code,language) VALUES ('kk-latn','qazaqşa (latın)');
REPLACE INTO language (iso_code,language) VALUES ('kk-tr','qazaqşa (Türkïya)');
REPLACE INTO language (iso_code,language) VALUES ('kl','kalaallisut');
REPLACE INTO language (iso_code,language) VALUES ('km','ភាសាខ្មែរ');
REPLACE INTO language (iso_code,language) VALUES ('kn','ಕನ್ನಡ');
REPLACE INTO language (iso_code,language) VALUES ('ko','한국어');
REPLACE INTO language (iso_code,language) VALUES ('ko-kp','조선말');
REPLACE INTO language (iso_code,language) VALUES ('koi','перем коми');
REPLACE INTO language (iso_code,language) VALUES ('kr','kanuri');
REPLACE INTO language (iso_code,language) VALUES ('krc','къарачай-малкъар');
REPLACE INTO language (iso_code,language) VALUES ('kri','Krio');
REPLACE INTO language (iso_code,language) VALUES ('krj','Kinaray-a');
REPLACE INTO language (iso_code,language) VALUES ('krl','karjal');
REPLACE INTO language (iso_code,language) VALUES ('ks','कॉशुर / کٲشُر');
REPLACE INTO language (iso_code,language) VALUES ('ks-arab','کٲشُر');
REPLACE INTO language (iso_code,language) VALUES ('ks-deva','कॉशुर');
REPLACE INTO language (iso_code,language) VALUES ('ksh','Ripoarisch');
REPLACE INTO language (iso_code,language) VALUES ('ksw','စှီၤ');
REPLACE INTO language (iso_code,language) VALUES ('ku','kurdî');
REPLACE INTO language (iso_code,language) VALUES ('ku-arab','كوردي (عەرەبی)');
REPLACE INTO language (iso_code,language) VALUES ('ku-latn','kurdî (latînî)');
REPLACE INTO language (iso_code,language) VALUES ('kum','къумукъ');
REPLACE INTO language (iso_code,language) VALUES ('kv','коми');
REPLACE INTO language (iso_code,language) VALUES ('kw','kernowek');
REPLACE INTO language (iso_code,language) VALUES ('ky','кыргызча');
REPLACE INTO language (iso_code,language) VALUES ('la','Latina');
REPLACE INTO language (iso_code,language) VALUES ('lad','Ladino');
REPLACE INTO language (iso_code,language) VALUES ('lb','Lëtzebuergesch');
REPLACE INTO language (iso_code,language) VALUES ('lbe','лакку');
REPLACE INTO language (iso_code,language) VALUES ('lez','лезги');
REPLACE INTO language (iso_code,language) VALUES ('lfn','Lingua Franca Nova');
REPLACE INTO language (iso_code,language) VALUES ('lg','Luganda');
REPLACE INTO language (iso_code,language) VALUES ('li','Limburgs');
REPLACE INTO language (iso_code,language) VALUES ('lij','Ligure');
REPLACE INTO language (iso_code,language) VALUES ('liv','Līvõ kēļ');
REPLACE INTO language (iso_code,language) VALUES ('lki','لەکی');
REPLACE INTO language (iso_code,language) VALUES ('lld','Ladin');
REPLACE INTO language (iso_code,language) VALUES ('lmo','lombard');
REPLACE INTO language (iso_code,language) VALUES ('ln','lingála');
REPLACE INTO language (iso_code,language) VALUES ('lo','ລາວ');
REPLACE INTO language (iso_code,language) VALUES ('loz','Silozi');
REPLACE INTO language (iso_code,language) VALUES ('lrc','لۊری شومالی');
REPLACE INTO language (iso_code,language) VALUES ('lt','lietuvių');
REPLACE INTO language (iso_code,language) VALUES ('ltg','latgaļu');
REPLACE INTO language (iso_code,language) VALUES ('lus','Mizo ţawng');
REPLACE INTO language (iso_code,language) VALUES ('luz','لئری دوٙمینی');
REPLACE INTO language (iso_code,language) VALUES ('lv','latviešu');
REPLACE INTO language (iso_code,language) VALUES ('lzh','文言');
REPLACE INTO language (iso_code,language) VALUES ('lzz','Lazuri');
REPLACE INTO language (iso_code,language) VALUES ('mad','Madhurâ');
REPLACE INTO language (iso_code,language) VALUES ('mag','मगही');
REPLACE INTO language (iso_code,language) VALUES ('mai','मैथिली');
REPLACE INTO language (iso_code,language) VALUES ('map-bms','Basa Banyumasan');
REPLACE INTO language (iso_code,language) VALUES ('mdf','мокшень');
REPLACE INTO language (iso_code,language) VALUES ('mg','Malagasy');
REPLACE INTO language (iso_code,language) VALUES ('mh','Ebon');
REPLACE INTO language (iso_code,language) VALUES ('mhr','олык марий');
REPLACE INTO language (iso_code,language) VALUES ('mi','Māori');
REPLACE INTO language (iso_code,language) VALUES ('min','Minangkabau');
REPLACE INTO language (iso_code,language) VALUES ('mk','македонски');
REPLACE INTO language (iso_code,language) VALUES ('ml','മലയാളം');
REPLACE INTO language (iso_code,language) VALUES ('mn','монгол');
REPLACE INTO language (iso_code,language) VALUES ('mni','ꯃꯤꯇꯩ ꯂꯣꯟ');
REPLACE INTO language (iso_code,language) VALUES ('mnw','ဘာသာ မန်');
REPLACE INTO language (iso_code,language) VALUES ('mo','молдовеняскэ');
REPLACE INTO language (iso_code,language) VALUES ('mos','moore');
REPLACE INTO language (iso_code,language) VALUES ('mr','मराठी');
REPLACE INTO language (iso_code,language) VALUES ('mrh','Mara');
REPLACE INTO language (iso_code,language) VALUES ('mrj','кырык мары');
REPLACE INTO language (iso_code,language) VALUES ('ms','Bahasa Melayu');
REPLACE INTO language (iso_code,language) VALUES ('ms-arab','بهاس ملايو');
REPLACE INTO language (iso_code,language) VALUES ('mt','Malti');
REPLACE INTO language (iso_code,language) VALUES ('mus','Mvskoke');
REPLACE INTO language (iso_code,language) VALUES ('mwl','Mirandés');
REPLACE INTO language (iso_code,language) VALUES ('my','မြန်မာဘာသာ');
REPLACE INTO language (iso_code,language) VALUES ('myv','эрзянь');
REPLACE INTO language (iso_code,language) VALUES ('mzn','مازِرونی');
REPLACE INTO language (iso_code,language) VALUES ('na','Dorerin Naoero');
REPLACE INTO language (iso_code,language) VALUES ('nah','Nāhuatl');
REPLACE INTO language (iso_code,language) VALUES ('nan','Bân-lâm-gú');
REPLACE INTO language (iso_code,language) VALUES ('nap','Napulitano');
REPLACE INTO language (iso_code,language) VALUES ('nb','norsk bokmål');
REPLACE INTO language (iso_code,language) VALUES ('nds','Plattdüütsch');
REPLACE INTO language (iso_code,language) VALUES ('nds-nl','Nedersaksies');
REPLACE INTO language (iso_code,language) VALUES ('ne','नेपाली');
REPLACE INTO language (iso_code,language) VALUES ('new','नेपाल भाषा');
REPLACE INTO language (iso_code,language) VALUES ('ng','Oshiwambo');
REPLACE INTO language (iso_code,language) VALUES ('nia','Li Niha');
REPLACE INTO language (iso_code,language) VALUES ('niu','Niuē');
REPLACE INTO language (iso_code,language) VALUES ('nl','Nederlands');
REPLACE INTO language (iso_code,language) VALUES ('nl-informal','Nederlands (informeel)');
REPLACE INTO language (iso_code,language) VALUES ('nmz','nawdm');
REPLACE INTO language (iso_code,language) VALUES ('nn','norsk nynorsk');
REPLACE INTO language (iso_code,language) VALUES ('no','norsk');
REPLACE INTO language (iso_code,language) VALUES ('nod','ᨣᩤᩴᨾᩮᩬᩥᨦ');
REPLACE INTO language (iso_code,language) VALUES ('nov','Novial');
REPLACE INTO language (iso_code,language) VALUES ('nqo','ߒߞߏ');
REPLACE INTO language (iso_code,language) VALUES ('nrm','Nouormand');
REPLACE INTO language (iso_code,language) VALUES ('nso','Sesotho sa Leboa');
REPLACE INTO language (iso_code,language) VALUES ('nv','Diné bizaad');
REPLACE INTO language (iso_code,language) VALUES ('ny','Chi-Chewa');
REPLACE INTO language (iso_code,language) VALUES ('nyn','runyankore');
REPLACE INTO language (iso_code,language) VALUES ('nys','Nyunga');
REPLACE INTO language (iso_code,language) VALUES ('oc','occitan');
REPLACE INTO language (iso_code,language) VALUES ('ojb','Ojibwemowin');
REPLACE INTO language (iso_code,language) VALUES ('olo','livvinkarjala');
REPLACE INTO language (iso_code,language) VALUES ('om','Oromoo');
REPLACE INTO language (iso_code,language) VALUES ('or','ଓଡ଼ିଆ');
REPLACE INTO language (iso_code,language) VALUES ('os','ирон');
REPLACE INTO language (iso_code,language) VALUES ('pa','ਪੰਜਾਬੀ');
REPLACE INTO language (iso_code,language) VALUES ('pag','Pangasinan');
REPLACE INTO language (iso_code,language) VALUES ('pam','Kapampangan');
REPLACE INTO language (iso_code,language) VALUES ('pap','Papiamentu');
REPLACE INTO language (iso_code,language) VALUES ('pcd','Picard');
REPLACE INTO language (iso_code,language) VALUES ('pcm','Naijá');
REPLACE INTO language (iso_code,language) VALUES ('pdc','Deitsch');
REPLACE INTO language (iso_code,language) VALUES ('pdt','Plautdietsch');
REPLACE INTO language (iso_code,language) VALUES ('pfl','Pälzisch');
REPLACE INTO language (iso_code,language) VALUES ('pi','पालि');
REPLACE INTO language (iso_code,language) VALUES ('pih','Norfuk / Pitkern');
REPLACE INTO language (iso_code,language) VALUES ('pl','polski');
REPLACE INTO language (iso_code,language) VALUES ('pms','Piemontèis');
REPLACE INTO language (iso_code,language) VALUES ('pnb','پنجابی');
REPLACE INTO language (iso_code,language) VALUES ('pnt','Ποντιακά');
REPLACE INTO language (iso_code,language) VALUES ('prg','prūsiskan');
REPLACE INTO language (iso_code,language) VALUES ('ps','پښتو');
REPLACE INTO language (iso_code,language) VALUES ('pt','português');
REPLACE INTO language (iso_code,language) VALUES ('pt-br','português do Brasil');
REPLACE INTO language (iso_code,language) VALUES ('pwn','pinayuanan');
REPLACE INTO language (iso_code,language) VALUES ('qu','Runa Simi');
REPLACE INTO language (iso_code,language) VALUES ('qug','Runa shimi');
REPLACE INTO language (iso_code,language) VALUES ('rgn','Rumagnôl');
REPLACE INTO language (iso_code,language) VALUES ('rif','Tarifit');
REPLACE INTO language (iso_code,language) VALUES ('rki','ရခိုင်');
REPLACE INTO language (iso_code,language) VALUES ('rm','rumantsch');
REPLACE INTO language (iso_code,language) VALUES ('rmc','romaňi čhib');
REPLACE INTO language (iso_code,language) VALUES ('rmy','romani čhib');
REPLACE INTO language (iso_code,language) VALUES ('rn','ikirundi');
REPLACE INTO language (iso_code,language) VALUES ('ro','română');
REPLACE INTO language (iso_code,language) VALUES ('roa-rup','armãneashti');
REPLACE INTO language (iso_code,language) VALUES ('roa-tara','tarandíne');
REPLACE INTO language (iso_code,language) VALUES ('rsk','руски');
REPLACE INTO language (iso_code,language) VALUES ('ru','русский');
REPLACE INTO language (iso_code,language) VALUES ('rue','русиньскый');
REPLACE INTO language (iso_code,language) VALUES ('rup','armãneashti');
REPLACE INTO language (iso_code,language) VALUES ('ruq','Vlăheşte');
REPLACE INTO language (iso_code,language) VALUES ('ruq-cyrl','Влахесте');
REPLACE INTO language (iso_code,language) VALUES ('ruq-latn','Vlăheşte');
REPLACE INTO language (iso_code,language) VALUES ('rw','Ikinyarwanda');
REPLACE INTO language (iso_code,language) VALUES ('ryu','うちなーぐち');
REPLACE INTO language (iso_code,language) VALUES ('sa','संस्कृतम्');
REPLACE INTO language (iso_code,language) VALUES ('sah','саха тыла');
REPLACE INTO language (iso_code,language) VALUES ('sat','ᱥᱟᱱᱛᱟᱲᱤ');
REPLACE INTO language (iso_code,language) VALUES ('sc','sardu');
REPLACE INTO language (iso_code,language) VALUES ('scn','sicilianu');
REPLACE INTO language (iso_code,language) VALUES ('sco','Scots');
REPLACE INTO language (iso_code,language) VALUES ('sd','سنڌي');
REPLACE INTO language (iso_code,language) VALUES ('sdc','Sassaresu');
REPLACE INTO language (iso_code,language) VALUES ('sdh','کوردی خوارگ');
REPLACE INTO language (iso_code,language) VALUES ('se','davvisámegiella');
REPLACE INTO language (iso_code,language) VALUES ('se-fi','davvisámegiella (Suoma bealde)');
REPLACE INTO language (iso_code,language) VALUES ('se-no','davvisámegiella (Norgga bealde)');
REPLACE INTO language (iso_code,language) VALUES ('se-se','davvisámegiella (Ruoŧa bealde)');
REPLACE INTO language (iso_code,language) VALUES ('sei','Cmique Itom');
REPLACE INTO language (iso_code,language) VALUES ('ses','Koyraboro Senni');
REPLACE INTO language (iso_code,language) VALUES ('sg','Sängö');
REPLACE INTO language (iso_code,language) VALUES ('sgs','žemaitėška');
REPLACE INTO language (iso_code,language) VALUES ('sh','srpskohrvatski / српскохрватски');
REPLACE INTO language (iso_code,language) VALUES ('sh-cyrl','српскохрватски (ћирилица)');
REPLACE INTO language (iso_code,language) VALUES ('sh-latn','srpskohrvatski (latinica)');
REPLACE INTO language (iso_code,language) VALUES ('shi','Taclḥit');
REPLACE INTO language (iso_code,language) VALUES ('shi-latn','Taclḥit');
REPLACE INTO language (iso_code,language) VALUES ('shi-tfng','ⵜⴰⵛⵍⵃⵉⵜ');
REPLACE INTO language (iso_code,language) VALUES ('shn','ၽႃႇသႃႇတႆး ');
REPLACE INTO language (iso_code,language) VALUES ('shy','tacawit');
REPLACE INTO language (iso_code,language) VALUES ('shy-latn','tacawit');
REPLACE INTO language (iso_code,language) VALUES ('si','සිංහල');
REPLACE INTO language (iso_code,language) VALUES ('simple','Simple English');
REPLACE INTO language (iso_code,language) VALUES ('sjd','кӣллт са̄мь кӣлл');
REPLACE INTO language (iso_code,language) VALUES ('sje','bidumsámegiella');
REPLACE INTO language (iso_code,language) VALUES ('sk','slovenčina');
REPLACE INTO language (iso_code,language) VALUES ('skr','سرائیکی');
REPLACE INTO language (iso_code,language) VALUES ('skr-arab','سرائیکی');
REPLACE INTO language (iso_code,language) VALUES ('sl','slovenščina');
REPLACE INTO language (iso_code,language) VALUES ('sli','Schläsch');
REPLACE INTO language (iso_code,language) VALUES ('sm','Gagana Samoa');
REPLACE INTO language (iso_code,language) VALUES ('sma','åarjelsaemien');
REPLACE INTO language (iso_code,language) VALUES ('smn','anarâškielâ');
REPLACE INTO language (iso_code,language) VALUES ('sms','nuõrttsääʹmǩiõll');
REPLACE INTO language (iso_code,language) VALUES ('sn','chiShona');
REPLACE INTO language (iso_code,language) VALUES ('so','Soomaaliga');
REPLACE INTO language (iso_code,language) VALUES ('sq','shqip');
REPLACE INTO language (iso_code,language) VALUES ('sr','српски / srpski');
REPLACE INTO language (iso_code,language) VALUES ('sr-ec','српски (ћирилица)');
REPLACE INTO language (iso_code,language) VALUES ('sr-el','srpski (latinica)');
REPLACE INTO language (iso_code,language) VALUES ('srn','Sranantongo');
REPLACE INTO language (iso_code,language) VALUES ('sro','sardu campidanesu');
REPLACE INTO language (iso_code,language) VALUES ('ss','SiSwati');
REPLACE INTO language (iso_code,language) VALUES ('st','Sesotho');
REPLACE INTO language (iso_code,language) VALUES ('stq','Seeltersk');
REPLACE INTO language (iso_code,language) VALUES ('sty','себертатар');
REPLACE INTO language (iso_code,language) VALUES ('su','Sunda');
REPLACE INTO language (iso_code,language) VALUES ('sv','svenska');
REPLACE INTO language (iso_code,language) VALUES ('sw','Kiswahili');
REPLACE INTO language (iso_code,language) VALUES ('syl','ꠍꠤꠟꠐꠤ');
REPLACE INTO language (iso_code,language) VALUES ('szl','ślůnski');
REPLACE INTO language (iso_code,language) VALUES ('szy','Sakizaya');
REPLACE INTO language (iso_code,language) VALUES ('ta','தமிழ்');
REPLACE INTO language (iso_code,language) VALUES ('tay','Tayal');
REPLACE INTO language (iso_code,language) VALUES ('tcy','ತುಳು');
REPLACE INTO language (iso_code,language) VALUES ('tdd','ᥖᥭᥰᥖᥬᥳᥑᥨᥒᥰ');
REPLACE INTO language (iso_code,language) VALUES ('te','తెలుగు');
REPLACE INTO language (iso_code,language) VALUES ('tet','tetun');
REPLACE INTO language (iso_code,language) VALUES ('tg','тоҷикӣ');
REPLACE INTO language (iso_code,language) VALUES ('tg-cyrl','тоҷикӣ');
REPLACE INTO language (iso_code,language) VALUES ('tg-latn','tojikī');
REPLACE INTO language (iso_code,language) VALUES ('th','ไทย');
REPLACE INTO language (iso_code,language) VALUES ('ti','ትግርኛ');
REPLACE INTO language (iso_code,language) VALUES ('tk','Türkmençe');
REPLACE INTO language (iso_code,language) VALUES ('tl','Tagalog');
REPLACE INTO language (iso_code,language) VALUES ('tly','tolışi');
REPLACE INTO language (iso_code,language) VALUES ('tly-cyrl','толыши');
REPLACE INTO language (iso_code,language) VALUES ('tn','Setswana');
REPLACE INTO language (iso_code,language) VALUES ('to','lea faka-Tonga');
REPLACE INTO language (iso_code,language) VALUES ('tok','toki pona');
REPLACE INTO language (iso_code,language) VALUES ('tpi','Tok Pisin');
REPLACE INTO language (iso_code,language) VALUES ('tr','Türkçe');
REPLACE INTO language (iso_code,language) VALUES ('tru','Ṫuroyo');
REPLACE INTO language (iso_code,language) VALUES ('trv','Seediq');
REPLACE INTO language (iso_code,language) VALUES ('ts','Xitsonga');
REPLACE INTO language (iso_code,language) VALUES ('tt','татарча/tatarça');
REPLACE INTO language (iso_code,language) VALUES ('tt-cyrl','татарча');
REPLACE INTO language (iso_code,language) VALUES ('tt-latn','tatarça');
REPLACE INTO language (iso_code,language) VALUES ('tum','chiTumbuka');
REPLACE INTO language (iso_code,language) VALUES ('tw','Twi');
REPLACE INTO language (iso_code,language) VALUES ('ty','reo tahiti');
REPLACE INTO language (iso_code,language) VALUES ('tyv','тыва дыл');
REPLACE INTO language (iso_code,language) VALUES ('tzm','ⵜⴰⵎⴰⵣⵉⵖⵜ');
REPLACE INTO language (iso_code,language) VALUES ('udm','удмурт');
REPLACE INTO language (iso_code,language) VALUES ('ug','ئۇيغۇرچە / Uyghurche');
REPLACE INTO language (iso_code,language) VALUES ('ug-arab','ئۇيغۇرچە');
REPLACE INTO language (iso_code,language) VALUES ('ug-latn','Uyghurche');
REPLACE INTO language (iso_code,language) VALUES ('uk','українська');
REPLACE INTO language (iso_code,language) VALUES ('ur','اردو');
REPLACE INTO language (iso_code,language) VALUES ('uz','oʻzbekcha/ўзбекча');
REPLACE INTO language (iso_code,language) VALUES ('uz-cyrl','ўзбекча');
REPLACE INTO language (iso_code,language) VALUES ('uz-latn','oʻzbekcha');
REPLACE INTO language (iso_code,language) VALUES ('ve','Tshivenda');
REPLACE INTO language (iso_code,language) VALUES ('vec','vèneto');
REPLACE INTO language (iso_code,language) VALUES ('vep','vepsän kel’');
REPLACE INTO language (iso_code,language) VALUES ('vi','Tiếng Việt');
REPLACE INTO language (iso_code,language) VALUES ('vls','West-Vlams');
REPLACE INTO language (iso_code,language) VALUES ('vmf','Mainfränkisch');
REPLACE INTO language (iso_code,language) VALUES ('vmw','emakhuwa');
REPLACE INTO language (iso_code,language) VALUES ('vo','Volapük');
REPLACE INTO language (iso_code,language) VALUES ('vot','Vaďďa');
REPLACE INTO language (iso_code,language) VALUES ('vro','võro');
REPLACE INTO language (iso_code,language) VALUES ('wa','walon');
REPLACE INTO language (iso_code,language) VALUES ('war','Winaray');
REPLACE INTO language (iso_code,language) VALUES ('wls','Fakaʻuvea');
REPLACE INTO language (iso_code,language) VALUES ('wo','Wolof');
REPLACE INTO language (iso_code,language) VALUES ('wuu','吴语');
REPLACE INTO language (iso_code,language) VALUES ('xal','хальмг');
REPLACE INTO language (iso_code,language) VALUES ('xh','isiXhosa');
REPLACE INTO language (iso_code,language) VALUES ('xmf','მარგალური');
REPLACE INTO language (iso_code,language) VALUES ('xsy','saisiyat');
REPLACE INTO language (iso_code,language) VALUES ('yi','ייִדיש');
REPLACE INTO language (iso_code,language) VALUES ('yo','Yorùbá');
REPLACE INTO language (iso_code,language) VALUES ('yrl','Nhẽẽgatú');
REPLACE INTO language (iso_code,language) VALUES ('yue','粵語');
REPLACE INTO language (iso_code,language) VALUES ('za','Vahcuengh');
REPLACE INTO language (iso_code,language) VALUES ('zea','Zeêuws');
REPLACE INTO language (iso_code,language) VALUES ('zgh','ⵜⴰⵎⴰⵣⵉⵖⵜ ⵜⴰⵏⴰⵡⴰⵢⵜ');
REPLACE INTO language (iso_code,language) VALUES ('zh','中文');
REPLACE INTO language (iso_code,language) VALUES ('zh-classical','文言');
REPLACE INTO language (iso_code,language) VALUES ('zh-cn','中文（中国大陆）');
REPLACE INTO language (iso_code,language) VALUES ('zh-hans','中文（简体）');
REPLACE INTO language (iso_code,language) VALUES ('zh-hant','中文（繁體）');
REPLACE INTO language (iso_code,language) VALUES ('zh-hk','中文（香港）');
REPLACE INTO language (iso_code,language) VALUES ('zh-min-nan','Bân-lâm-gú');
REPLACE INTO language (iso_code,language) VALUES ('zh-mo','中文（澳門）');
REPLACE INTO language (iso_code,language) VALUES ('zh-my','中文（马来西亚）');
REPLACE INTO language (iso_code,language) VALUES ('zh-sg','中文（新加坡）');
REPLACE INTO language (iso_code,language) VALUES ('zh-tw','中文（臺灣）');
REPLACE INTO language (iso_code,language) VALUES ('zh-yue','粵語');
REPLACE INTO language (iso_code,language) VALUES ('zu','isiZulu' );
REPLACE INTO language (iso_code,language) VALUES ('other','other' );
